packages:
  - apps/*
  - packages/*
  - remotion

allowBuilds:
  better-sqlite3: true
  esbuild: true
  ffmpeg-ffprobe-static: true
  sharp: true

minimumReleaseAgeExclude:
  - remotion@4.0.513
  - "@remotion/bundler@4.0.513"
  - "@remotion/captions@4.0.513"
  - "@remotion/compositor-darwin-arm64@4.0.513"
  - "@remotion/compositor-darwin-x64@4.0.513"
  - "@remotion/compositor-linux-arm64-gnu@4.0.513"
  - "@remotion/compositor-linux-arm64-musl@4.0.513"
  - "@remotion/compositor-linux-x64-gnu@4.0.513"
  - "@remotion/compositor-linux-x64-musl@4.0.513"
  - "@remotion/compositor-win32-x64-msvc@4.0.513"
  - "@remotion/licensing@4.0.513"
  - "@remotion/media-parser@4.0.513"
  - "@remotion/media-utils@4.0.513"
  - "@remotion/player@4.0.513"
  - "@remotion/renderer@4.0.513"
  - "@remotion/streaming@4.0.513"
  - "@remotion/studio-protocol@4.0.513"
  - "@remotion/studio-shared@4.0.513"
  - "@remotion/studio@4.0.513"
  - "@remotion/timeline-utils@4.0.513"
  - "@remotion/web-renderer@4.0.513"
  - "@remotion/zod-types@4.0.513"
